### ISSUE TITLE
`mass app new` creates dev params / auto files

### ISSUE THREAD

**Issue by WillBeebe** [massdriver-cloud/massdriver-cli#113]
Right now we copy and render application templates but don't add any other files. 

`mass app new` should add these files to each Terraform step

+ `_connections.auto.tfvars.json` 
+ `_params.auto.tfvars.json`

**Comment by coryodaniel** [comment]
#114 We are going to be moving some of the commands around a bit.

I think we have a few options:

1. manually add these to each template, is nice because we can actually flesh them out a bit, but tedious.
2. after the application or bundle is created (mass bundle new, mass app new - for now), we should have in the CLI a set of add'l files that need to be added to for local development, for each step loop and add the files for that provisioner type.

**Comment by WillBeebe** [comment]
I'd say manually add for now, automate in a week or two.

**Comment by WillBeebe** [comment]
Closing this, Jake's work w/ creating the params file from massdriver.yaml solves this in a great way.
